version: '3.3'
networks:
  testNetwork:
    driver: bridge

services:
  SolitaDB:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ='GMT+3'
      - PGTZ='GMT+3'
    volumes:
      -

        type: bind
        source: ./postgres_data
        target: /var/lib/postgresql/data
