version: '3.3'
networks:
  testNetwork:
    driver: bridge

services:
  Radiance:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      -

        type: bind
        source: ./testData/postgres_data
        target: /var/lib/postgresql/data
